# Generated by Django 6.0 on 2026-07-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0018_guildconfig_manual_drop_enabled'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchPhraseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('cost', models.PositiveBigIntegerField(help_text='Currency paid for this phrase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catch Phrase Log',
                'verbose_name_plural': 'Catch Phrase Logs',
            },
        ),
        migrations.CreateModel(
            name='PlayerCatchPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player Catch Phrase',
                'verbose_name_plural': 'Player Catch Phrases',
            },
        ),
        migrations.CreateModel(
            name='SpawnBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.PositiveBigIntegerField(help_text='Discord guild this boost applies to')),
                ('multiplier', models.FloatField(help_text='Spawn rate multiplier (2.0 = double spawns)')),
                ('expires_at', models.DateTimeField(help_text='When this boost stops applying')),
                ('source', models.CharField(choices=[('purchase', 'Shop purchase'), ('admin', 'Staff command')], default='purchase', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spawn Boost',
                'verbose_name_plural': 'Spawn Boosts',
            },
        ),
        migrations.RenameIndex(
            model_name='currencytransaction',
            new_name='currency_cu_player__97e882_idx',
            old_name='currency_cu_player__b3f3d1_idx',
        ),
        migrations.RenameIndex(
            model_name='currencytransaction',
            new_name='currency_cu_created_740b4c_idx',
            old_name='currency_cu_created_9c1a7e_idx',
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='catch_phrase_cost',
            field=models.PositiveIntegerField(default=1000, help_text='Cost of setting (or replacing) a custom catch phrase'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='catch_phrase_enabled',
            field=models.BooleanField(default=True, help_text='Allow buying a custom catch phrase from the shop'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='catch_phrase_max_length',
            field=models.PositiveIntegerField(default=100, help_text='Maximum length of a custom catch phrase'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='reroll_base_cost',
            field=models.PositiveIntegerField(default=500, help_text='Cost of the first stat reroll on a collectible'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='reroll_cost_escalation',
            field=models.BooleanField(default=True, help_text='Multiply the cost by the reroll number (2nd reroll costs 2x base, 3rd costs 3x)'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='reroll_enabled',
            field=models.BooleanField(default=True, help_text='Allow buying stat rerolls from the shop'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='reroll_max_per_ball',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of stat rerolls a single collectible can receive'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='spawn_boost_cost',
            field=models.PositiveIntegerField(default=2000, help_text='Cost of a server-wide spawn boost'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='spawn_boost_duration_hours',
            field=models.FloatField(default=6.0, help_text='Duration in hours of a purchased spawn boost'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='spawn_boost_enabled',
            field=models.BooleanField(default=True, help_text='Allow buying a server-wide spawn boost from the shop'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='spawn_boost_multiplier',
            field=models.FloatField(default=2.0, help_text='Spawn rate multiplier applied by a purchased boost'),
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='source',
            field=models.CharField(choices=[('catch', 'Catch bounty'), ('daily', 'Daily reward'), ('sell', 'Sell'), ('reroll', 'Shop: stat reroll'), ('catch_phrase', 'Shop: catch phrase'), ('spawn_boost', 'Shop: spawn boost')], max_length=16),
        ),
        migrations.AddField(
            model_name='catchphraselog',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_phrase_logs', to='bd_models.player'),
        ),
        migrations.AddField(
            model_name='playercatchphrase',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_catch_phrase', to='bd_models.player'),
        ),
        migrations.AddField(
            model_name='spawnboost',
            name='purchased_by',
            field=models.ForeignKey(blank=True, help_text='Player who bought the boost (empty for staff boosts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawn_boosts', to='bd_models.player'),
        ),
        migrations.AddIndex(
            model_name='catchphraselog',
            index=models.Index(fields=['player', 'created_at'], name='currency_ca_player__cf2dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='spawnboost',
            index=models.Index(fields=['guild_id', 'expires_at'], name='currency_sp_guild_i_7266a8_idx'),
        ),
    ]
