# Generated by Django 6.0 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_catchphraselog_playercatchphrase_spawnboost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysettings',
            name='shop_enabled',
            field=models.BooleanField(default=False, help_text='Register the shop command group with Discord. Leave this off while configuring shop prices, then enable it and resync the command tree to make it live.'),
        ),
    ]
